### PR TITLE
Adding fixture loader

### PR DESCRIPTION
**Pull request by mamazu**
Now you can define a list of fixtures the current fixture depends on.
This is thanks to @JakobTolkemit.

### CODE REVIEW

**Comment by pamil** [comment]
I'm not sure if I understand this PR correctly, could you add an example configuration (or add docs for the new feature)?

**Comment by JakobTolkemit** [comment]
It's a suite loader.
You can add it to the listeners section of a suite to define other fixture suites that should be loaded first.

```yaml
sylius_fixtures:
  suites:
    a:
      listeners:
        suite_loader:
          options:
            suites:
            - 'b'
      fixtures:
        ...
    b:
      fixtures:
        ...
```
In this example, when you want to load the `a` suite, it would load the `b` suite before loading `a`.

**Comment by mamazu** [comment]
Thanks Jakob, I added it to the documentation.

**Comment by mamazu** [comment]
What about this one?
@pamil

**Comment by mamazu** [comment]
Yeah I thought about this as well. Will be done.

**Comment by lchrusciel** [comment]
e2e is something we should introduce to this library itself.  We should introduce the mocked application and try to use fixtures inside. Something similar can be found here: https://github.com/Sylius/SyliusResourceBundle/tree/master/src/Bundle/test/src/Tests/Controller or https://github.com/Sylius/SyliusGridBundle/tree/master/src/Bundle/Tests or https://github.com/Sylius/SyliusGridBundle/blob/master/src/Bundle/Tests/Functional/GridApiTest.php

But in case of fixtures, I'm thinking about some class creation and fixtures to them and then load + asserting, that they are in the database. The biggest problem is to build a scaffolding for it. Once we will have it, we just need to add example usage for new features.

But it is a separate concern from the root of this PR.

**Comment by mamazu** [comment]
Yeah this could be easily achieved when mocking the database to be in memory and then asserting that certain objects are persisted. But I totally agree that these tests would be quite helpful to see.

**Comment by lchrusciel** [comment]
Thanks, @mamazu! :1st_place_medal:

**Pull request merged**
